repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs

-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        language_version: python3.11
        args: [--line-length=88]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [
            --fix,
            --exit-non-zero-on-fix,
            --target-version, "py311"
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies:
        - types-all
        - pydantic
        - fastapi

-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args: ["--no-update"]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true

    -   id: coverage-check
        name: coverage-check
        entry: poetry run pytest --cov=src --cov-fail-under=80
        language: system
        pass_filenames: false
        always_run: true

# Docker specific checks
-   repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0
    hooks:
    -   id: hadolint
        args: ['--ignore', 'DL3008', '--ignore', 'DL3013']

# Kubernetes and Helm specific checks
-   repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.3
    hooks:
    -   id: helm-docs

-   repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.1.9
    hooks:
    -   id: checkov
        args: [
            '--framework', 'kubernetes',
            '--skip-check', 'CKV_K8S_37',
            '--quiet',
            '--compact'
        ]