version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 10s

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION:-latest}
    # image: ${DOCKER_REGISTRY:-ghcr.io}/${GITHUB_USERNAME:-lethanhson9901}/${IMAGE_NAME:-app-source}:${BRANCH:-main}_${BUILD_VERSION:-1.0.0}
    image: ghcr.io/lethanhson9901/app-source:main_1.0.0
    pull_policy: always  # Changed to always pull
    container_name: python-app
    env_file: .env
    environment:
      - APP_ENV=production
      - TZ=UTC
    ports:
      - "8080:8080"
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
    logging: *default-logging
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /app/logs:size=100M

networks:
  default:
    name: python-app-network
