name: Cleanup Old Images

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  cleanup:
    name: Cleanup Old Images
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete failed CI images
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.request('GET /user/packages?package_type=container', {
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });

            const appPackage = response.data.find(pkg => pkg.name === 'app-source');
            if (appPackage) {
              const versions = await github.request('GET /user/packages/{package_type}/{package_name}/versions', {
                package_type: 'container',
                package_name: 'app-source',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              });

              for (const version of versions.data) {
                if (version.metadata.container.tags.some(tag => tag.startsWith('sha256:'))) {
                  try {
                    await github.request('DELETE /user/packages/{package_type}/{package_name}/versions/{version_id}', {
                      package_type: 'container',
                      package_name: 'app-source',
                      version_id: version.id,
                      headers: {
                        'X-GitHub-Api-Version': '2022-11-28'
                      }
                    });
                    console.log(`Deleted SHA tagged version ${version.id}`);
                  } catch (error) {
                    console.log(`Error deleting version ${version.id}: ${error.message}`);
                  }
                }
              }
            }

      - name: Keep only last 5 images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'app-source'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
