name: Cleanup Container Images

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - '*'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete sha256 prefixed images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'app-source'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            [
              {
                "type": "name",
                "pattern": "^sha256:"
              }
            ]

      - name: Keep only latest 5 tagged images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'app-source'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            [
              {
                "type": "name",
                "pattern": "^(?!sha256:).*$"
              }
            ]
